import type { Board } from './board'
import { moveDestinations } from './geometry'
import type { Geometry, TeamId, Vec2 } from './types'

class MinHeap {
  private items: number[] = []
  private priority: Float64Array

  constructor(size: number) {
    this.priority = new Float64Array(size)
  }

  get size(): number {
    return this.items.length
  }

  push(node: number, prio: number): void {
    this.priority[node] = prio
    this.items.push(node)
    let i = this.items.length - 1
    while (i > 0) {
      const parent = (i - 1) >> 1
      if (this.priority[this.items[parent]] <= this.priority[this.items[i]]) break
      const tmp = this.items[parent]
      this.items[parent] = this.items[i]
      this.items[i] = tmp
      i = parent
    }
  }

  pop(): number {
    const top = this.items[0]
    const last = this.items.pop() as number
    if (this.items.length > 0) {
      this.items[0] = last
      let i = 0
      const n = this.items.length
      for (;;) {
        const l = i * 2 + 1
        const r = l + 1
        let smallest = i
        if (l < n && this.priority[this.items[l]] < this.priority[this.items[smallest]]) smallest = l
        if (r < n && this.priority[this.items[r]] < this.priority[this.items[smallest]]) smallest = r
        if (smallest === i) break
        const tmp = this.items[smallest]
        this.items[smallest] = this.items[i]
        this.items[i] = tmp
        i = smallest
      }
    }
    return top
  }
}

function heuristic(ax: number, ay: number, bx: number, by: number): number {
  return Math.max(Math.abs(ax - bx), Math.abs(ay - by))
}

export interface PathResult {
  cells: Vec2[]
  found: boolean
  expanded: number
}

/**
 * A* over the graph induced by a piece's movement geometry. Neighbour moves are
 * generated by `moveDestinations` with occupancy ignored, so routes may be
 * planned through cells that are merely busy right now; the movement system
 * waits/replans if a step is actually blocked.
 */
export function findPath(board: Board, from: Vec2, to: Vec2, geom: Geometry, team: TeamId): PathResult {
  const w = board.width
  const h = board.height
  const size = w * h
  const gScore = new Float64Array(size).fill(Infinity)
  const cameFrom = new Int32Array(size).fill(-1)
  const closed = new Uint8Array(size)
  const heap = new MinHeap(size)

  const startIdx = from.y * w + from.x
  const goalIdx = to.y * w + to.x
  if (startIdx === goalIdx) return { cells: [], found: true, expanded: 0 }

  gScore[startIdx] = 0
  heap.push(startIdx, heuristic(from.x, from.y, to.x, to.y))

  let expanded = 0
  let bestIdx = startIdx
  let bestH = heuristic(from.x, from.y, to.x, to.y)

  while (heap.size > 0) {
    const current = heap.pop()
    if (closed[current]) continue
    closed[current] = 1
    expanded++

    if (current === goalIdx) {
      bestIdx = current
      bestH = 0
      break
    }

    const cx = current % w
    const cy = (current - cx) / w
    const hh = heuristic(cx, cy, to.x, to.y)
    if (hh < bestH) {
      bestH = hh
      bestIdx = current
    }

    const neighbours = moveDestinations(board, { x: cx, y: cy }, geom, team, undefined, true)
    for (const n of neighbours) {
      const nIdx = n.y * w + n.x
      if (closed[nIdx]) continue
      const tentative = gScore[current] + board.moveCost(n.x, n.y)
      if (tentative < gScore[nIdx]) {
        gScore[nIdx] = tentative
        cameFrom[nIdx] = current
        heap.push(nIdx, tentative + heuristic(n.x, n.y, to.x, to.y))
      }
    }
  }

  if (bestH > 0 && bestIdx !== goalIdx) {
    // goal was unreachable; walk back from the closest cell reached and report
    // the partial route so the piece advances rather than stalling.
  }

  const cells: Vec2[] = []
  let node = bestIdx
  while (node !== startIdx && node !== -1) {
    const x = node % w
    const y = (node - x) / w
    cells.push({ x, y })
    node = cameFrom[node]
  }
  cells.reverse()

  if (bestIdx !== goalIdx) return { cells, found: false, expanded }
  return { cells, found: true, expanded }
}
